name: 'Comment'
description: 'Renders a comment, optionally with a patch file'
inputs:
  template_name:
     description: 'The name of the comment template'
     default: '' 
  template_data:  
    description: 'JSON string of template variables'
    default: ''
  file_data:  
    description: 'JSON string mapping keys to file paths'
    default: ''
outputs:
  comment:
    description: 'The rendered comment'
runs:
  using: 'node20'
  main: 'index.js'